name: DSF5
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - pandas
  - scikit-learn
  - tensorflow=2.1
  - umap-learn
  - scipy 
  - pip:
    - requests
